### ISSUE TITLE
Couldn't buy new token 

### ISSUE THREAD

**Issue by manuelhb14** [CryptoGnome/LimitSwap#108]
2021-02-27 01:03:25.987512Could not format value {'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached'} as field 'abi'
2021-02-27 01:03:31.502986Could not format value None as field 'abi'
2021-02-27 01:03:34.876639("The function 'allowance' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
Traceback (most recent call last):
  File "eth_utils\applicators.py", line 84, in apply_formatters_to_dict
  File "web3\_utils\normalizers.py", line 243, in normalize_abi
  File "web3\_utils\validation.py", line 73, in validate_abi
ValueError: 'abi' is not a list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "limitswap.py", line 663, in start_bot
  File "web3\eth.py", line 532, in contract
  File "web3\contract.py", line 360, in factory
  File "web3\_utils\datatypes.py", line 54, in __new__
  File "eth_utils\functional.py", line 45, in inner
  File "eth_utils\applicators.py", line 86, in apply_formatters_to_dict
ValueError: Could not format value {'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached'} as field 'abi'

**Comment by manuelhb14** [comment]
The token had a proxy contract, I think this was the reason "allowance" was not available in the contract.

**Comment by CryptoGnome** [comment]
fixing today
