### ISSUE TITLE
Error on Sell

### ISSUE THREAD

**Issue by sidework** [CryptoGnome/LimitSwap#11]
I got this error, and it asked me to put it on GitHub. 

INFO - 2020-10-17 22:50:45,792 - NEW STARTUP v2.5
INFO - 2020-10-17 22:50:46,131 - Using <web3.main.Web3 object at 0x000001B68AD52C40> ('mainnet')
INFO - 2020-10-17 22:50:46,361 - Using factory contract: <web3._utils.datatypes.Contract object at 0x000001B68AD5DAC0>
INFO - 2020-10-17 22:50:46,831 - Using <web3.main.Web3 object at 0x000001B68AE22FD0> ('mainnet')
INFO - 2020-10-17 22:50:46,944 - Using factory contract: <web3._utils.datatypes.Contract object at 0x000001B68AE11880>
INFO - 2020-10-17 22:50:47,508 - Starting Pro Bot
INFO - 2020-10-17 22:50:51,709 - Adding New ABI'S to Assets Folder to Reduce API calls, ignore restarts  as this might take a few cycles and this is normal 
INFO - 2020-10-17 22:50:52,379 - Starting Pro Bot
INFO - 2020-10-17 23:31:52,965 - Approving 0xbD03BD923c7D51019Fd84571D84e4eBcf7213509...
ERROR - 2020-10-17 23:32:10,620 - Insufficient balance. Had 253350994033414137414, needed 253350994033414144000
Traceback (most recent call last):
  File "eth_utils\applicators.py", line 84, in apply_formatters_to_dict
  File "web3\_utils\normalizers.py", line 243, in normalize_abi
  File "web3\_utils\validation.py", line 73, in validate_abi
ValueError: 'abi' is not a list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "limitswap.py", line 88, in check_decimals
  File "web3\eth.py", line 532, in contract
  File "web3\contract.py", line 360, in factory
  File "web3\_utils\datatypes.py", line 54, in __new__
  File "eth_utils\functional.py", line 45, in inner
  File "eth_utils\applicators.py", line 86, in apply_formatters_to_dict
ValueError: Could not format value None as field 'abi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 342, in start_bot
  File "limitswap.py", line 306, in start_many
  File "limitswap.py", line 147, in run_bot
  File "limitswap.py", line 268, in sell
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 456, in make_trade
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 253350994033414137414, needed 253350994033414144000

**Comment by CryptoGnome** [comment]
Can you please provide me with you token settings for this as well as the wallet address, or the amount of tokens and eth you had when attempting this trade

**Comment by sidework** [comment]
Here's the txn where I sold it since it flaked: 0x814e8d447eeae5b374bbbb75bf389207b7717dd3f3cb840df6fa68f3f8d3fd3c
I don't have the token settings anymore (since i sold it), but I had it set to just sell everything when it it hit x.

**Comment by CryptoGnome** [comment]
Fixed in todays release
