### ISSUE TITLE
BSC - Error when launching from a VPS

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#118]
Hi,
When I try to launch it on my OVH VPS, I have this error : 

ERROR: 2021-04-02 09:16:15,934 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 257, in <module>
  File "main.py", line 245, in auth
  File "main.py", line 210, in run_pro
  File "main.py", line 175, in quote_usd
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

It's very strange because the SAME folder works on my Mac via Parallels Desktop...

**Comment by CryptoGnome** [comment]
resolved
