### ISSUE TITLE
BSC - Error "KeyError: 'tx' " when when trying to buy AIOZ

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#122]
Hi, i'm getting this error, when trying to buy AIOZ:

```
INFO: 2021-04-03 16:49:30,686 Current Tokens Staked = 55.0
INFO: 2021-04-03 16:49:30,687 Trader Price = 50 Tokens Staked
ERROR: 2021-04-03 16:49:32,961 'tx'
Traceback (most recent call last):
  File "main.py", line 257, in <module>
  File "main.py", line 245, in auth
  File "main.py", line 218, in run_pro
  File "main.py", line 142, in buy
KeyError: 'tx'
```

With this settings:

```
"SYMBOL": "AIOZ",
"ADDRESS": "0x33d08D8C7a168333a85285a68C0042b39fC3741D",
"BASESYMBOL": "BUSD",
"BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
"BUYAMOUNT": "10",
"MAXAMOUNT": "9.7",
"BUYPRICE": "2.05",
"SELLAMOUNT": "4.7",
"SELLPRICE": "2.2",
"MOONBAG": "0",
"SLIPPAGE": "3",
"USECHAI": "false",
"GASBOOST": "25",
"GASLIMIT": "250000",
"MAXGAS": "50"
```

**Comment by CryptoGnome** [comment]
resolved
