### ISSUE TITLE
BSC - Error "sell() missing 1 required positional argument: 'token' " when when trying to buy POOCOIN

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#123]
when I try to buy POOCOIN, I have this error : 

```
INFO: 2021-04-03 19:24:35,201 Current Tokens Staked = 100.0
INFO: 2021-04-03 19:24:35,201 Trader Price = 50 Tokens Staked
ERROR: 2021-04-03 19:24:35,873 sell() missing 1 required positional argument: 'token'
Traceback (most recent call last):
  File "main.py", line 257, in <module>
  File "main.py", line 245, in auth
  File "main.py", line 222, in run_pro
TypeError: sell() missing 1 required positional argument: 'token'
```

Here is my token.json :  

```
[
  {
    "SYMBOL": "POOCOIN",
    "ADDRESS": "0xb27adaffb9fea1801459a1a81b17218288c097cc",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNT": "1",
    "MAXAMOUNT": "0.5",
    "BUYPRICE": "0.50",
    "SELLAMOUNT": "25",
    "SELLPRICE": "0.80",
    "MOONBAG": "0",
    "SLIPPAGE": "3",
    "USECHAI": "false",
    "GASBOOST": "25",
    "GASLIMIT": "500",
    "MAXGAS": "500"
  }
]

```

**Comment by CryptoGnome** [comment]
are you on the most recent version?

**Comment by CryptoGnome** [comment]
resolved
