### ISSUE TITLE
BSC Error trying to run main.exe in version 0.4 

### ISSUE THREAD

**Issue by GlimSpan** [CryptoGnome/LimitSwap#125]
ERROR: 2021-04-04 00:26:13,998 quote_usd() missing 1 required positional argument: 'amountIn'
Traceback (most recent call last):
  File "main.py", line 312, in <module>
  File "main.py", line 303, in auth
  File "main.py", line 245, in run_trader
TypeError: quote_usd() missing 1 required positional argument: 'amountIn'

**Comment by CryptoGnome** [comment]
resolved
