### ISSUE TITLE
Cannot load library libsecp256k1.dll error 0x7e

### ISSUE THREAD

**Issue by thereyrey** [CryptoGnome/LimitSwap#128]
INFO: 2021-04-05 13:42:05,128 Current Tokens Staked = 25.0
INFO: 2021-04-05 13:42:05,128 Trader Price = 50 Tokens Staked
ERROR: 2021-04-05 13:42:08,227 cannot load library 'C:\Users\User\AppData\Local\Temp\_MEI201402\coincurve\libsecp256k1.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI201402\\coincurve\\libsecp256k1.dll'
Traceback (most recent call last):
  File "main.py", line 358, in <module>
  File "main.py", line 349, in auth
  File "main.py", line 274, in run_trader
  File "main.py", line 63, in check_approval
  File "main.py", line 73, in approve
  File "main.py", line 129, in transmit
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 603, in signTransaction
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 647, in sign_transaction
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 246, in from_key
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 694, in _parsePrivateKey
  File "eth_keys\datatypes.py", line 257, in __init__
  File "eth_keys\datatypes.py", line 102, in backend
  File "eth_keys\datatypes.py", line 113, in get_backend
  File "eth_keys\backends\__init__.py", line 35, in get_backend
  File "eth_keys\backends\__init__.py", line 29, in get_backend_class
  File "eth_keys\backends\__init__.py", line 19, in get_default_backend_class
  File "eth_keys\backends\coincurve.py", line 34, in is_coincurve_available
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\oimap\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "coincurve\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\oimap\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "coincurve\context.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\oimap\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "coincurve\flags.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\oimap\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "coincurve\_libsecp256k1.py", line 239, in <module>
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'C:\Users\User\AppData\Local\Temp\_MEI201402\coincurve\libsecp256k1.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI201402\\coincurve\\libsecp256k1.dll'

**Comment by CryptoGnome** [comment]
Resolved
