### ISSUE TITLE
Error on Sell & Buy - Insufficient Balance

### ISSUE THREAD

**Issue by goneale** [CryptoGnome/LimitSwap#13]
Plenty of balance for GAS.

Initially I thought this was just on SELL, turns out it occured on BUY as well. This is strange, as it is after already one successful sell out about 30 minutes prior. Log updated with both sell and re-buy attempts.

![image](https://user-images.githubusercontent.com/107109/96411076-3d85ba80-122b-11eb-961c-6835acae51bb.png)

```
{
        "BUYPAIR": "0x0000000000000000000000000000000000000000",
        "BUYSYMBOL": "ETH",
        "USEMANY": "true",
        "USESTOPLOSS": "false",
        "MAXGAS": "200",
        "SLIPPAGE": "5",
        "GASBOOST": "35",
        "GASLIMIT": "250000",
...
```

```
{
        "ADDRESS": "0x6051c1354ccc51b4d561e43b02735deae64768b8",
        "SYMBOL": "yRise",
        "SELLPRICE": "24",
        "BUYPRICE": "15",
        "MAXTOKENS": "0.0001",
        "BUYAMOUNT": "14.28",
        "STOPLOSS": "90",
        "MOONBAG": "0",
        "ID": "yRise"
    }
```

```
INFO - 2020-10-19 16:49:03,685 - NEW STARTUP v2.5
INFO - 2020-10-19 16:49:04,843 - Using <web3.main.Web3 object at 0x00000258ABD3FCA0> ('mainnet')
INFO - 2020-10-19 16:49:05,147 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000258ABD4CB20>
INFO - 2020-10-19 16:49:06,093 - Using <web3.main.Web3 object at 0x00000258ABE12F40> ('mainnet')
INFO - 2020-10-19 16:49:06,480 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000258ABE00850>
INFO - 2020-10-19 16:49:08,354 - Starting Basic Bot
ERROR - 2020-10-19 16:49:10,833 - Insufficient balance. Had 10228596429800854551, needed 10228596429800855552
Traceback (most recent call last):
  File "limitswap.py", line 350, in start_bot
  File "limitswap.py", line 292, in start
  File "limitswap.py", line 186, in run_bot
  File "limitswap.py", line 268, in sell
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 456, in make_trade
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 10228596429800854551, needed 10228596429800855552
INFO - 2020-10-19 16:49:47,637 - NEW STARTUP v2.5
INFO - 2020-10-19 16:49:48,762 - Using <web3.main.Web3 object at 0x00000233972FFCA0> ('mainnet')
INFO - 2020-10-19 16:49:49,055 - Using factory contract: <web3._utils.datatypes.Contract object at 0x000002339730CB20>
INFO - 2020-10-19 16:49:49,825 - Using <web3.main.Web3 object at 0x00000233973D2F40> ('mainnet')
INFO - 2020-10-19 16:49:50,024 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000233973C0850>
INFO - 2020-10-19 16:49:51,627 - Starting Basic Bot
INFO - 2020-10-19 16:58:49,472 - NEW STARTUP v2.5
INFO - 2020-10-19 16:58:50,649 - Using <web3.main.Web3 object at 0x0000020FF06EFCA0> ('mainnet')
INFO - 2020-10-19 16:58:50,940 - Using factory contract: <web3._utils.datatypes.Contract object at 0x0000020FF06FCB20>
INFO - 2020-10-19 16:58:51,878 - Using <web3.main.Web3 object at 0x0000020FF07C2F40> ('mainnet')
INFO - 2020-10-19 16:58:52,082 - Using factory contract: <web3._utils.datatypes.Contract object at 0x0000020FF07B0850>
INFO - 2020-10-19 16:58:53,349 - Starting Basic Bot
ERROR - 2020-10-19 17:03:08,553 - Insufficient balance. Had 1151049870560094210, needed 1178840923706091700
Traceback (most recent call last):
  File "limitswap.py", line 350, in start_bot
  File "limitswap.py", line 292, in start
  File "limitswap.py", line 193, in run_bot
  File "limitswap.py", line 239, in buy
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 452, in make_trade
  File "uniswap\uniswap.py", line 494, in _eth_to_token_swap_input
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 1151049870560094210, needed 1178840923706091700
INFO - 2020-10-19 17:03:09,757 - Starting Basic Bot
ERROR - 2020-10-19 17:03:12,239 - Insufficient balance. Had 1151049870560094210, needed 1178840923706091700
Traceback (most recent call last):
  File "limitswap.py", line 350, in start_bot
  File "limitswap.py", line 292, in start
  File "limitswap.py", line 193, in run_bot
  File "limitswap.py", line 239, in buy
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 452, in make_trade
  File "uniswap\uniswap.py", line 494, in _eth_to_token_swap_input
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 1151049870560094210, needed 1178840923706091700

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 350, in start_bot
  File "limitswap.py", line 292, in start
  File "limitswap.py", line 193, in run_bot
  File "limitswap.py", line 239, in buy
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 452, in make_trade
  File "uniswap\uniswap.py", line 494, in _eth_to_token_swap_input
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 1151049870560094210, needed 1178840923706091700
INFO - 2020-10-19 17:03:34,213 - NEW STARTUP v2.5
INFO - 2020-10-19 17:03:35,353 - Using <web3.main.Web3 object at 0x000001AB070CFCA0> ('mainnet')
INFO - 2020-10-19 17:03:35,649 - Using factory contract: <web3._utils.datatypes.Contract object at 0x000001AB070DCB20>
INFO - 2020-10-19 17:03:36,431 - Using <web3.main.Web3 object at 0x000001AB071A2F40> ('mainnet')
INFO - 2020-10-19 17:03:36,639 - Using factory contract: <web3._utils.datatypes.Contract object at 0x000001AB07190850>
INFO - 2020-10-19 17:03:37,882 - Starting Basic Bot

```

**Comment by CryptoGnome** [comment]
Found a Decimal issue, pushing fix for this today!

Thanks for the amazing report!
