### ISSUE TITLE
BSC - No such file or directory: './abi/factory.json'

### ISSUE THREAD

**Issue by thereyrey** [CryptoGnome/LimitSwap#132]
ERROR: 2021-04-06 17:50:52,761 [Errno 2] No such file or directory: './abi/factory.json'
Traceback (most recent call last):
  File "main.py", line 400, in <module>
  File "main.py", line 391, in auth
  File "main.py", line 326, in run_trader
  File "main.py", line 214, in buy
  File "main.py", line 118, in check_pool
FileNotFoundError: [Errno 2] No such file or directory: './abi/factory.json'

Crashed on a buy. Waiting for TX.

**Comment by thereyrey** [comment]
Also happens on buy order.

**Comment by CryptoGnome** [comment]
fixed
