### ISSUE TITLE
Error while trying to run the bot

### ISSUE THREAD

**Issue by gukenji** [CryptoGnome/LimitSwap#141]
Hi, when I try to run the bot I keep getting this error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 713, in start_bot
  File "limitswap.py", line 150, in pre_approve
  File "uniswap\uniswap.py", line 765, in approve
  File "uniswap\uniswap.py", line 800, in _build_and_send_tx
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 647, in sign_transaction
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 246, in from_key
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 694, in _parsePrivateKey
  File "eth_keys\datatypes.py", line 257, in __init__
  File "eth_keys\datatypes.py", line 102, in backend
  File "eth_keys\datatypes.py", line 113, in get_backend
  File "eth_keys\backends\__init__.py", line 35, in get_backend
  File "eth_keys\backends\__init__.py", line 29, in get_backend_class
  File "eth_keys\backends\__init__.py", line 19, in get_default_backend_class
  File "eth_keys\backends\coincurve.py", line 34, in is_coincurve_available
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "coincurve\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "coincurve\context.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "coincurve\flags.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "coincurve\_libsecp256k1.py", line 239, in <module>
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'C:\Users\guga\OneDrive\Área de Trabalho\LimitSwap\LimitSwap\coincurve\libsecp256k1.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\guga\\OneDrive\\Área de Trabalho\\LimitSwap\\LimitSwap\\coincurve\\libsecp256k1.dll'

What can I do?

Thanks!

**Comment by gukenji** [comment]
I'm using the version v.2933

**Comment by gukenji** [comment]
Oh, just a note: if I leave "pre-approve" on it doesnt work. When I turn it off it work
