### ISSUE TITLE
ETH v 2.935 - approval was called and burned gas. repeatedly, until i saw that and shut down the bot

### ISSUE THREAD

**Issue by skerni** [CryptoGnome/LimitSwap#146]
**approval is burning 0.017 eth**
2021-04-13 17:29:04.921916 Wallet Balance:**1.250**0600686222345Ethereum
2021-04-13 17:29:05.046585 BUYINGPUSH
2021-04-13 17:29:17.330744Insufficient balance. Had 1233033968622234449, needed 1342509801463852000
Traceback (most recent call last):
  File "limitswap.py", line 715, in start_bot
  File "limitswap.py", line 653, in start_many
  File "limitswap.py", line 248, in limit_orders
  File "limitswap.py", line 401, in buy
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 452, in make_trade
  File "uniswap\uniswap.py", line 494, in _eth_to_token_swap_input
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 1233033968622234449, needed 1342509801463852000
2021-04-13 17:29:18.867586 Wallet Balance:**1.233**0339686222345Ethereum

**SETTINGS**: default, useboost = off, **BUT** i did import settings from v2.90, otherwise did not change the settings.json

**at the same time, before the liquidity was added i received this error message:**
2021-04-13 16:53:00.483179'USEBOOST'
Traceback (most recent call last):
  File "limitswap.py", line 713, in start_bot
  File "limitswap.py", line 150, in pre_approve
  File "uniswap\uniswap.py", line 765, in approve
  File "uniswap\uniswap.py", line 798, in _build_and_send_tx
  File "uniswap\uniswap.py", line 863, in _get_tx_params
  File "uniswap\uniswap.py", line 838, in check_gas
KeyError: 'USEBOOST'
2021-04-13 16:53:01.196953'USEBOOST'
Traceback (most recent call last):
  File "limitswap.py", line 713, in start_bot
  File "limitswap.py", line 150, in pre_approve
  File "uniswap\uniswap.py", line 765, in approve
  File "uniswap\uniswap.py", line 798, in _build_and_send_tx
  File "uniswap\uniswap.py", line 863, in _get_tx_params
  File "uniswap\uniswap.py", line 838, in check_gas
KeyError: 'USEBOOST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 713, in start_bot
  File "limitswap.py", line 150, in pre_approve
  File "uniswap\uniswap.py", line 765, in approve
  File "uniswap\uniswap.py", line 798, in _build_and_send_tx
  File "uniswap\uniswap.py", line 863, in _get_tx_params
  File "uniswap\uniswap.py", line 838, in check_gas

**it looks like the import of settings file corrupted the setting useboost, which in turn corruopted the IsApproved variable or smth. Since the token was added with preapproval turned on, it was approved (i checked etherscan). then regardless of this, every other attempt to buy (succesful or not) called approval again**

**Comment by CryptoGnome** [comment]
you need to use the newest settings file, we will fix the import function
