### ISSUE TITLE
Issue with buying BOSON

### ISSUE THREAD

**Issue by TXKO** [CryptoGnome/LimitSwap#150]
2021-04-15 09:31:19.611987 Max Position Reached for ghoul Skipping for now...
2021-04-15 09:31:20.311281 Wallet Balance:0.6446830495838655Ethereum
2021-04-15 09:31:20.362770 BUYINGboson
2021-04-15 09:31:37.418048'<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "limitswap.py", line 715, in start_bot
  File "limitswap.py", line 653, in start_many
  File "limitswap.py", line 248, in limit_orders
  File "limitswap.py", line 438, in buy
TypeError: '<' not supported between instances of 'int' and 'str'
2021-04-15 09:34:20.886665 Wallet Balance:0.6419115409838655Ethereum
2021-04-15 09:34:20.934434 Max Position Reached for NFY Skipping for now...
2021-04-15 09:34:21.780595 Wallet Balance:0.6419115409838655Ethereum
2021-04-15 09:34:21.831271 Max Position Reached for BDP Skipping for now...
2021-04-15 09:34:25.343641 Wallet Balance:0.6419115409838655Ethereum
2021-04-15 09:34:25.395836 Max Position Reached for LABS Skipping for now...

![image](https://user-images.githubusercontent.com/82598683/114892071-0ce59e80-9dd2-11eb-9dcf-927034b11b8a.png)

**Comment by TXKO** [comment]
used V2.935 of the limitbot 
![image](https://user-images.githubusercontent.com/82598683/114891996-fc352880-9dd1-11eb-9db3-7cf13707377d.png)

**Comment by CryptoGnome** [comment]
fixed
