### ISSUE TITLE
Error running v2.63: 429 Too Many Requests

### ISSUE THREAD

**Issue by sidework** [CryptoGnome/LimitSwap#16]
Just so that the error is logged... we talked on Discord... on execute, no mods from release besides settings and token ( I don't use the Flask app, but I got the same when I tried it):

V:\VMShared\source\sideworktech\LimitSwap\limitswap>limitswap
Traceback (most recent call last):
  File "limitswap.py", line 391, in <module>
  File "uniswap\uniswap.py", line 158, in __init__
  File "web3\net.py", line 44, in version
  File "web3\module.py", line 44, in caller
  File "web3\manager.py", line 149, in request_blocking
  File "web3\manager.py", line 128, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\gas_price_strategy.py", line 34, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\exception_retry_request.py", line 105, in middleware
  File "web3\providers\rpc.py", line 92, in make_request
  File "web3\_utils\request.py", line 40, in make_post_request
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://mainnet.infura.io/v3/c210309d4958412daa27cb66260d4c54
[34276] Failed to execute script limitswap

**Comment by CryptoGnome** [comment]
resolved
