### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by TXKO** [CryptoGnome/LimitSwap#168]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 637, in urlopen
  File "urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CryptoGnome/LimitSwap/releases/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E26FB74B50>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 868, in <module>
  File "limitswap.py", line 95, in check_release
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 60, in request
  File "requests\sessions.py", line 533, in request
  File "requests\sessions.py", line 646, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CryptoGnome/LimitSwap/releases/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E26FB74B50>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))
[11876] Failed to execute script limitswap
[extra.log](https://github.com/CryptoGnome/LimitSwap/files/6371210/extra.log)
[errors.log](https://github.com/CryptoGnome/LimitSwap/files/6371211/errors.log)

**Comment by CryptoGnome** [comment]
fixing in next version
