### ISSUE TITLE
Crashing at lunch (BSC v2.9363)

### ISSUE THREAD

**Issue by RioJanairo** [CryptoGnome/LimitSwap#169]
Hello I got this error at lunch  : 

my token.json : 
[
  {
"SYMBOL": "KPAD",    
"ADDRESS": "0xcfefa64b0ddd611b125157c41cd3827f2e8e8615",    
"BASESYMBOL": "WBNB", 
"BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
"BUYAMOUNT": "1",    
"MAXAMOUNT": "2.5",
"BUYPRICE": "0.001",
"SELLAMOUNT": "1000",    
"SELLPRICE": "0.002",    
"MOONBAG": "0",    
"SLIPPAGE": "0.5", 
"GAS": "7",
"LIQUIDITYCHECK": "FALSE",
"LIQUIDTYWBNB": "100"
  }
]

the error log : 
INFO: 2021-04-26 15:21:49,130 *************************************************************************************
INFO: 2021-04-26 15:21:49,130 For Help & To Learn More About how the bot works please visit our wiki here:
INFO: 2021-04-26 15:21:49,130 https://limitswap.gitbook.io/limitswap/
INFO: 2021-04-26 15:21:49,130 *************************************************************************************
INFO: 2021-04-26 15:21:49,295 Here is Latest Release Version  on Github Please Make Sure You are Staying Updated = v2.9363
INFO: 2021-04-26 15:21:51,174 Current Tokens Staked = 50.0
INFO: 2021-04-26 15:21:51,175 Trader Price = 50 Tokens Staked
ERROR: 2021-04-26 15:21:54,272 'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'
ERROR: 2021-04-26 15:21:54,272 'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'

exception.log : 
'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'
'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'
'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'
'SETTINGSCHECKER'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 454, in run_pro
KeyError: 'SETTINGSCHECKER'

**Comment by CryptoGnome** [comment]
use new settings.json file with download

**Comment by RioJanairo** [comment]
thx , 

    "SETTINGSCHECKER": "TRUE" was missing
