### ISSUE TITLE
Could not transact with/call contract function, is contract deployed correctly and chain synced?

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#181]
[
  {
  "SYMBOL": "ENX",
  "ADDRESS": "0xd0d7a9f2021958e51d60d6966b7bbed9d1cb22b5",
  "BASESYMBOL": "WETH",
  "BASEADDRESS": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
  "BUYAMOUNTINBASE": "0.1",
  "BUYPRICEINBASE": "0.0000001",
  "SELLAMOUNT": "ALL",
  "SELLPRICEINBASE": "0.000423431",
  "MAXTOKENS": "0.00001",
  "MOONBAG": "0",
  "SLIPPAGE": "12",
  "HASFEES": "false",
  "GAS": "BOOST",
  "BOOSTPERCENT": "10",
  "GASLIMIT": "400000",
  "LIQUIDTYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

this token is listed

but I have the error :

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "LimitSwap.py", line 590, in run
  File "LimitSwap.py", line 358, in preapprove
  File "LimitSwap.py", line 256, in check_approval
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1529, in call_contract_function
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
ERROR: 2021-05-01 02:51:08,105 Could not transact with/call contract function, is contract deployed correctly and chain synced?
Traceback (most recent call last):
  File "web3\contract.py", line 1507, in call_contract_function
  File "eth_abi\codec.py", line 181, in decode_abi
  File "eth_abi\decoding.py", line 127, in call
  File "eth_utils\functional.py", line 45, in inner
  File "eth_abi\decoding.py", line 173, in decode
  File "eth_abi\decoding.py", line 127, in call
  File "eth_abi\decoding.py", line 198, in decode
  File "eth_abi\decoding.py", line 305, in read_data_from_stream
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "LimitSwap.py", line 590, in run
  File "LimitSwap.py", line 358, in preapprove
  File "LimitSwap.py", line 256, in check_approval
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1529, in call_contract_function
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

in my settings.json :  "EXCHANGE": "uniswap",

**Comment by CryptoGnome** [comment]
you used the wrong address for WETH.

here is the correct one:
https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
