### ISSUE TITLE
Specific contract prevents bot from running "Before" contract is released on PCS V2.

### ISSUE THREAD

**Issue by CryptoDynasty** [CryptoGnome/LimitSwap#184]
Everything has been testing fine, until I ran across this contract. 0x98a19a067063f13166204e867a7846474b7ca2b1 (Safe Charity).

When you start the bot, immediately the bot shuts down. This was in the error log.

ERROR: 2021-05-02 10:26:22,710 Python int too large to convert to C ssize_t
Traceback (most recent call last):
  File "LimitSwap.py", line 609, in run
  File "LimitSwap.py", line 316, in check_price
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1507, in call_contract_function
  File "eth_abi\codec.py", line 181, in decode_abi
  File "eth_abi\decoding.py", line 127, in call
  File "eth_utils\functional.py", line 45, in inner
  File "eth_abi\decoding.py", line 173, in decode
  File "eth_abi\decoding.py", line 127, in call
  File "eth_abi\decoding.py", line 144, in decode
  File "eth_abi\decoding.py", line 95, in push_frame
  File "eth_abi\decoding.py", line 84, in seek_in_frame
OverflowError: Python int too large to convert to C ssize_t

Token Settings:

  {
  "SYMBOL": "SFCT",
  "ADDRESS": "0x98a19a067063F13166204E867a7846474B7ca2b1",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "1",
  "BUYPRICEINBASE": "10",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "10",
  "MAXTOKENS": "1000000000000000000000",
  "MOONBAG": "0",
  "SLIPPAGE": "15",
  "HASFEES": "true",
  "GAS": "20",
  "BOOSTPERCENT": "10",
  "GASLIMIT": "300000",
  "LIQUIDITYCHECK": "true",
  "LIQUIDITYAMOUNT": "1"
  }

this was the only token I experienced this with.

**Comment by CryptoGnome** [comment]
fixed
