### ISSUE TITLE
getAmountsOut error

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/LimitSwap#209]
Today I had again this error. As added info: 

- I was able to buy 2,964.54 @0.46875 wBNBs
- The price hit 0.0017 (over my sellprice) and I got the error. I had setup to sell 900 tokens with a moonbag of 2000, so should be fine.

ERROR
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "LimitSwap.py", line 787, in run
  File "LimitSwap.py", line 607, in sell
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 

tokens.json 
  "SYMBOL": "CBD",
  "ADDRESS": "0x0e2b41ea957624a314108cc4e33703e9d78f4b3c",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "wBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.46875",
  "BUYPRICEINBASE": "0.00078125",

  "SELLAMOUNTINTOKENS": "900",
  "SELLPRICEINBASE": "0.0015625",

  "MAXTOKENS": "1",
  "MOONBAG": "2000",
  "SLIPPAGE": "49",
  "HASFEES": "false",
  "GAS": "50",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"

**Comment by CryptoGnome** [comment]
This is just slippage

**Comment by alefantozzi** [comment]
Please take a look, it happened before with me in different tokens. I was already using max (49) for slippage....

I really think it is something else. The bot found Sell Signal Sell Signal Found @0.0017346460.  Looking at the transactions, the price stayed pretty close to that (0.001711 the lowest) for the following 4 blocks....

Please let me know what other info you may need.

**Comment by alefantozzi** [comment]
Just FYI, I ran some testes and found out that the problem happens when SELLAMOUNTINTOKENS tries to sell close to what MOONBAG is set. Say I have 2500, put SELLAMOUNTINTOKENS 490 and MOONBAG 2000 it gives the error (maybe after calculating slipage). 

by the way, why is SELLAMOUNTINTOKENS needed? Just SELLPRICE and MOONBAG should be enough right?

**Comment by alefantozzi** [comment]
FYI the problem remains: no matter what slipage I use, it is IMPOSSIBLE to sell by selecting SELLAMOUNTINTOKENS. The only way it works is by leaving it to ALL and adjusting the amount on MOONBAG

**Comment by alexpo** [comment]
The same problem also seems to be when the number is close to the moonbag.
NETWORK ETH

++++++++++++
2021-06-05 19:07:08.943390 tokenname Price  0.879834 USDC
2021-06-05 19:07:09.926190 tokenname Price  0.879834 USDC
2021-06-05 19:07:11.657790 Current Wallet Balance is: 924.9767799195213 tokenname 
2021-06-05 19:07:11.657790 Sell Signal Found tokenname 
2021-06-05 19:07:11.657790 Placing Sell Order tokenname 
2021-06-05 19:07:12.328590 Current Wallet Balance is: 924.9767799195213 tokenname 
2021-06-05 19:07:14.091390 Current Wallet Balance is: 924.9767799195213 tokenname 
2021-06-05 19:07:14.091390 Selling 100 tokenname 
2021-06-05 19:07:14.730990 ERROR: Please Check Your Error & Exception Logs for m
ore info...
Restarting LimitSwap
++++++++++++++

===================
[   
  {
  "SYMBOL": "tokenname ",
  "ADDRESS": "0x12131231231",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "USDT",
  "BASEADDRESS": "0xdac17f958d2ee523a2206206994597c13d831ec7",
  "BUYAMOUNTINBASE": "3",
  "BUYPRICEINBASE": "0", 
  
  "SELLAMOUNTINTOKENS": "100",
  "SELLPRICEINBASE": "0.892", 
  
  "MAXTOKENS": "900",
  "MOONBAG": "800",
  "SLIPPAGE": "15",
  "HASFEES": "false",
  "GAS": "BOOST",
  "BOOSTPERCENT": "10",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "1000"
  }  
]
===================


++++++++++++++
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 819, in run
  File "LimitSwap.py", line 672, in sell
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
ERROR: 2021-06-05 19:07:14,730 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "LimitSwap.py", line 819, in run
  File "LimitSwap.py", line 672, in sell
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
