### ISSUE TITLE
Getting Errors on 3.09

### ISSUE THREAD

**Issue by TechJonesAi** [CryptoGnome/LimitSwap#212]
Hello GNOME Im getting errors with the BOT and not quite sure why. Please see code below. Thanks

Traceback (most recent call last):
  File "LimitSwap.py", line 691, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 3 (char 575)
ERROR: 2021-05-07 16:11:34,322 Expecting ',' delimiter: line 30 column 3 (char 575)
Traceback (most recent call last):
  File "LimitSwap.py", line 691, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 3 (char 575)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 691, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 3 (char 575)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[
  {
  "SYMBOL": "DOGE",
  "ADDRESS": "0xba2ae424d960c26247dd6c32edc70b295c744c43",
  
  "USECUSTOMBASEPAIR": "false",
  "BASESYMBOL": "BNB",
  "BASEADDRESS": "enter your custom Base pair address if USECUSTOMBASEPAIR =True",
  "BUYAMOUNTINBASE": "0.2",
  "BUYPRICEINBASE": "0.000996865",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "0.001800000",
  
  
  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "13",
  "HASFEES": "true",
  "GAS": "5",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "true",
  "LIQUIDITYAMOUNT": "10"
 } 

  {

**Comment by tsarbuig** [comment]
missing the "," between "}" and "{"...

**Comment by TechJonesAi** [comment]
Ok thanks, i got it sorted by pasting a fresh code again
