### ISSUE TITLE
Bot says not enough USDC when buying on quickswap even when there's plenty in wallet

### ISSUE THREAD

**Issue by Napkinss** [CryptoGnome/LimitSwap#273]
Error from logs:

ERROR: 2021-06-24 02:35:24,663 {'code': -32603, 'message': 'request failed or timed out'}
Traceback (most recent call last):
  File "LimitSwap.py", line 210, in decimals
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1499, in call_contract_function
  File "eth_utils\functional.py", line 45, in inner
  File "web3\eth.py", line 432, in call
  File "web3\manager.py", line 153, in request_blocking
ValueError: {'code': -32603, 'message': 'request failed or timed out'}
ERROR: 2021-06-24 02:35:24,663 local variable 'DECIMALS' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 791, in run
  File "LimitSwap.py", line 216, in decimals
UnboundLocalError: local variable 'DECIMALS' referenced before assignment
ERROR: 2021-06-24 02:35:24,663 local variable 'DECIMALS' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 791, in run
  File "LimitSwap.py", line 216, in decimals
UnboundLocalError: local variable 'DECIMALS' referenced before assignment
 

Bot Screenshot:

![photo_2021-06-24_02-40-51](https://user-images.githubusercontent.com/85951274/123266321-77cbf800-d52e-11eb-9e25-eef795d2da7e.jpg)

**Comment by CryptoGnome** [comment]
fixed next release
