### ISSUE TITLE
Weird Error - https://reverent-raman:photo-hamlet-ankle-saved-scared-bobbed

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/LimitSwap#280]
I got the following error today, which I've never seen. It was working ok the bot, I closed it and after reoppening (same settings/tokes, same version 3.18) is started happening:

erros.txt
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\buffered_gas_estimate.py", line 40, in middleware
  File "web3\middleware\exception_retry_request.py", line 104, in middleware
  File "web3\providers\rpc.py", line 88, in make_request
  File "web3\_utils\request.py", line 49, in make_post_request
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://reverent-raman:photo-hamlet-ankle-saved-scared-bobbed@nd-539-402-515.p2pify.com/
ERROR: 2021-07-01 15:52:04,314 500 Server Error: Internal Server Error for url: https://reverent-raman:photo-hamlet-ankle-saved-scared-bobbed@nd-539-402-515.p2pify.com/
Traceback (most recent call last):
  File "LimitSwap.py", line 919, in <module>
  File "LimitSwap.py", line 259, in auth
  File "web3\contract.py", line 957, in call
  File "web3\contract.py", line 1501, in call_contract_function
  File "web3\module.py", line 57, in caller
  File "web3\manager.py", line 156, in request_blocking
  File "web3\manager.py", line 135, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\gas_price_strategy.py", line 35, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\buffered_gas_estimate.py", line 40, in middleware
  File "web3\middleware\exception_retry_request.py", line 104, in middleware
  File "web3\providers\rpc.py", line 88, in make_request
  File "web3\_utils\request.py", line 49, in make_post_request
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://reverent-raman:photo-hamlet-ankle-saved-scared-bobbed@nd-539-402-515.p2pify.com/
INFO: 2021-07-01 15:52:04,330 Restarting LimitSwap

exceptions.txt
Traceback (most recent call last):
  File "LimitSwap.py", line 889, in run
NameError: name 'cooldown' is not defined
name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 919, in <module>
  File "LimitSwap.py", line 259, in auth
  File "web3\contract.py", line 957, in call
  File "web3\contract.py", line 1501, in call_contract_function
  File "web3\module.py", line 57, in caller
  File "web3\manager.py", line 156, in request_blocking
  File "web3\manager.py", line 135, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\gas_price_strategy.py", line 35, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\buffered_gas_estimate.py", line 40, in middleware
  File "web3\middleware\exception_retry_request.py", line 104, in middleware
  File "web3\providers\rpc.py", line 88, in make_request
  File "web3\_utils\request.py", line 49, in make_post_request
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://reverent-raman:photo-hamlet-ankle-saved-scared-bobbed@nd-539-402-515.p2pify.com/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 889, in run
NameError: name 'cooldown' is not defined

**Comment by CryptoGnome** [comment]
node was down this day, resolved
