### ISSUE TITLE
Python int too large to convert to C ssize_t Traceback (most recent call last):

### ISSUE THREAD

**Issue by NachoJSBSC** [CryptoGnome/LimitSwap#292]
ERROR: 2021-07-06 17:59:30,189 Python int too large to convert to C ssize_t
Traceback (most recent call last):
  File "LimitSwap.py", line 834, in run
  File "LimitSwap.py", line 515, in buy
  File "web3\contract.py", line 957, in call
  File "web3\contract.py", line 1513, in call_contract_function
  File "eth_abi\codec.py", line 181, in decode_abi
  File "eth_abi\decoding.py", line 127, in __call__
  File "eth_utils\functional.py", line 45, in inner
  File "eth_abi\decoding.py", line 173, in decode
  File "eth_abi\decoding.py", line 127, in __call__
  File "eth_abi\decoding.py", line 144, in decode
  File "eth_abi\decoding.py", line 95, in push_frame
  File "eth_abi\decoding.py", line 84, in seek_in_frame
OverflowError: Python int too large to convert to C ssize_t

-----------------

[
  {
  "SYMBOL": "DCB",
  "ADDRESS": "0xEAc9873291dDAcA754EA5642114151f3035c67A2",

  "USECUSTOMBASEPAIR": "false",  
  "BASESYMBOL": "enter here your custom Base pair symbol if USECUSTOMBASEPAIR =True",
  "BASEADDRESS": "enter here your custom Base pair address if USECUSTOMBASEPAIR =True",
  "BUYAMOUNTINBASE": "10",
  "BUYPRICEINBASE": "0.00007",
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "0.0000946294",
  
  "MAXTOKENS": "100000000",
  "MOONBAG": "30",
  "SLIPPAGE": "49",
  "HASFEES": "false",
  "GAS": "20",
  "BOOSTPERCENT": "50",
  "GASLIMIT": "1000000",
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

**Comment by CryptoGnome** [comment]
what was this on a buy or sell? this looks like an error with the smart contact. Also which exchange was this on

**Comment by NachoJSBSC** [comment]
it was a buy order on pancakeswap v2
