### ISSUE TITLE
Matic pair not recognizing

### ISSUE THREAD

**Issue by cryptoB3** [CryptoGnome/LimitSwap#326]
I have attached the token json here, very positive settings is correct as I use the bot actively for Uni and BSC purchases.
[
   {
  "SYMBOL": "MSHIT",
  "ADDRESS": "0xf239e69ce434c7fb408b05a0da416b14917d934e",
  
  "USECUSTOMBASEPAIR": "false",
  "BASESYMBOL": "MATIC",
  "BASEADDRESS": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "BUYAMOUNTINBASE": "200",
  "BUYPRICEINBASE": "10",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "1000004",
  
  
  "MAXTOKENS": "1500000000000000000000000000000",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "HASFEES": "true",
  "GAS": "50",
  "BOOSTPERCENT": "20",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
  ]

I see this in the exception Logs but no timestamp so don't know when this occurred

Invalid control character at: line 4 column 15 (char 42)
Traceback (most recent call last):
  File "LimitSwap.py", line 1008, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 15 (char 42)

**Comment by CryptoGnome** [comment]
is it a scam token?

**Comment by cryptoB3** [comment]
No it's not. See here, it's still trading. https://www.dextools.io/app/quickswap/pair-explorer/0x982c1f90381e31e7b7dbba8708126532b7cb7df6 I checked now, it's recognizing but don't know why it wasn't when the token launched. They had both MATIC and USDC liquidity, maybe that's why?
