### ISSUE TITLE
Sell order failure on LimitSwap v3.30 on BSC Smart Chain

### ISSUE THREAD

**Issue by SpenTappy** [CryptoGnome/LimitSwap#336]
Dear Crypto Gnome,

Please can you help with an urgent issue?

We are running v3.30 on Windows. Connected Metamask wallet using Smart Chain (BSC).
The sell price trigger is detected but the trade fails, as per below.  I believe buy orders succeeded.
XYZ is a fake token name.

`2021-08-28 23:10:22.155642 Checking Approval Status 0x...b2
2021-08-28 23:10:22.327517 Checking Approval Status 0x...55
2021-08-28 23:10:22.686909 PVM  Price  1.9332476817650561 USDT
2021-08-28 23:10:23.561920 Current Wallet Balance is: 5910.167558093094 XYZ
2021-08-28 23:10:23.561920 Sell Signal Found XYZ
2021-08-28 23:10:23.561920 Placing Sell Order XYZ
2021-08-28 23:10:23.921295 Current Wallet Balance is: 5910.167558093094 XYZ
2021-08-28 23:10:23.921295 Checking Approval Status 0x...2
2021-08-28 23:10:24.624415 Current Wallet Balance is: 5910.167558093094 XYZ
2021-08-28 23:10:24.624415 Selling 0.54 XYZ
2021-08-28 23:10:24.968203 ERROR: Please Check Your Error & Exception Logs for more info...
Restarting LimitSwap
.........Restart Cooldown left 10 seconds.............
...
.........Restart Cooldown left 0 seconds.............`

Meanwhile the error log always shows:

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 1181, in run
  File "LimitSwap.py", line 988, in sell
  File "web3\contract.py", line 876, in __call__
  File "web3\contract.py", line 881, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
INFO: 2021-08-28 23:15:06,023 Restarting LimitSwap`

------------------
**Settings:**

[
    {
        "LIMITWALLETPRIVATEKEY": "hidden",
        "LIMITWALLETADDRESS": "0x...7",
        "WALLETADDRESS": "0x...4",
        "PRIVATEKEY": "also_hidden",
        "USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "pancakeswap",
		"EXCHANGEVERSION": "2",
		"PREAPPROVE": "true",
		"UNLIMITEDSLIPPAGE": "false"
    }
]

**Tokens:**

[
  {
	  
  "ENABLED": "True",
  "SYMBOL": "XYZ",
  "ADDRESS": "0x...2",

  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "USDT",
  "BASEADDRESS": "0x55d398326f99059ff775485246999027b3197955",
  "LIQUIDITYINNATIVETOKEN": "False",
  "BUYAMOUNTINBASE": "1.0",
  "BUYPRICEINBASE": "1.65",

  "SELLAMOUNTINTOKENS": "0.54",
  "SELLPRICEINBASE": "1.85",
  
  
  "MAXTOKENS": "6500",
  "MOONBAG": "5880",
  "SLIPPAGE": "49",
  "HASFEES": "true",
  "GAS": "10",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

**Comment by CryptoGnome** [comment]
should be fixed in next release
