### ISSUE TITLE
ERROR: 2021-10-28 00:13:42,864 Expecting ',' delimiter: line 12 column 5 (char 297)

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#364]
Hi bro,

A user had this error and I cannot see what is wrong... user is using last version v3.35

It's an ETH token : https://etherscan.io/tx/0x928515cdc08071b25abf4bd60e34db320783198c9d8878d2c41f0431aba84ca3

I feel like it's BOOST option which does not work properly, what do you think ?

TOKENS.JSON
```
[
  {

    "ENABLED": "true",

    "SYMBOL": "Ryoshimoto",
    "ADDRESS": "0xf03F082Bf49fe71c2Ab8DFAf4F8d0AEAA1D3DE14",
    "BUYAMOUNTINBASE": "0.07",
    "BUYPRICEINBASE":  "1000",
    "SELLPRICEINBASE": "99999999",
    "SLIPPAGE": "49",

    "MAXTOKENS": "100",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "false",
    "LIQUIDITYAMOUNT": "10",
    "LIQUIDITYINNATIVETOKEN": "True",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "WETH",
    "BASEADDRESS": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "true",
    "GAS": "boost",
    "BOOSTPERCENT": "10",
    "GASLIMIT": "5000000"

  }
]

```

SETTINGS.JSON
```
[
    {
        "LIMITWALLETPRIVATEKEY": "",  (removed for privacy)
        "LIMITWALLETADDRESS": "",  (removed for privacy)
        "WALLETADDRESS": "",  (removed for privacy)
        "PRIVATEKEY": "",  (removed for privacy)
        "USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "Uniswap",
    "EXCHANGEVERSION": "1",
    "PREAPPROVE": "true",
    "UNLIMITEDSLIPPAGE": "false"
    }
]

```

ERROR LOG
Traceback (most recent call last):
  File "LimitSwap.py", line 1063, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 297)
INFO: 2021-10-28 00:13:31,750 Restarting LimitSwap
ERROR: 2021-10-28 00:13:42,864 Expecting ',' delimiter: line 12 column 5 (char 297)
Traceback (most recent call last):
  File "LimitSwap.py", line 1063, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 297)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 1063, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 297)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 1063, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 297)

**Comment by Zerusi** [comment]
@tsarbuig   https://github.com/eSwapping/ESWAP-Limit-Order-Bot/releases/ check that bot :)

**Comment by CryptoGnome** [comment]
this only happens when json is formatted incorrectly
