### ISSUE TITLE
Bot would not sell at sell trigger - 503 error / Could not format value

### ISSUE THREAD

**Issue by goneale** [CryptoGnome/LimitSwap#5]
These errors seem to be occurring about 10 minutes before the sell trigger and for around an hour after the sell trigger when digging back through the logs...

LimitSwap Beta v0.13

I have no idea if this affected why it didn't sell, but I had adequate ETH and a sound configuration.
```
  {
        "ADDRESS": "0xaa19673aa1b483a5c4f73b446b4f851629a7e7d6",
        "SYMBOL": "xETH",
        "BUYPRICE": 6.5,
        "SELLPRICE": 8.5,
        "MAXTOKENS": 0.0001,
        "BUYAMOUNT": 75,
        "STOPLOSS": 90,
        "MOONBAG": 10,
        "ID": "xETH"
    }
```

[FULL ERROR LOG HERE](https://drive.google.com/file/d/1wIp1z60xFGqfJGHbl7LVHdAMKoOOQVQe/view?usp=sharing). Excerpt below.

```
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://focused-bhabha:cramp-chill-curtly-sedan-cosmos-filler@nd-138-966-059.p2pify.com/
ERROR - 2020-10-11 07:42:28,478 - 503 Server Error: Service Temporarily Unavailable for url: https://focused-bhabha:cramp-chill-curtly-sedan-cosmos-filler@nd-138-966-059.p2pify.com/
Traceback (most recent call last):
  File "eth_utils\applicators.py", line 84, in apply_formatters_to_dict
  File "web3\_utils\normalizers.py", line 243, in normalize_abi
  File "web3\_utils\validation.py", line 73, in validate_abi
ValueError: 'abi' is not a list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "limitswap.py", line 329, in start_bot
  File "limitswap.py", line 270, in start
  File "limitswap.py", line 189, in run_bot
  File "limitswap.py", line 216, in buy
  File "limitswap.py", line 63, in check_balance
  File "web3\eth.py", line 532, in contract
  File "web3\contract.py", line 360, in factory
  File "web3\_utils\datatypes.py", line 54, in __new__
  File "eth_utils\functional.py", line 45, in inner
  File "eth_utils\applicators.py", line 86, in apply_formatters_to_dict
ValueError: Could not format value {'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached'} as field 'abi'
--
Traceback (most recent call last):
  File "eth_utils\applicators.py", line 84, in apply_formatters_to_dict
  File "web3\_utils\normalizers.py", line 243, in normalize_abi
  File "web3\_utils\validation.py", line 73, in validate_abi
ValueError: 'abi' is not a list
```

**Comment by CryptoGnome** [comment]
Fix in Place

**Comment by goneale** [comment]
Amazing, thanks
