### ISSUE TITLE
503 Server Error: Service Temporarily Unavailable for url: https://focused-bhabha...

### ISSUE THREAD

**Issue by goneale** [CryptoGnome/LimitSwap#6]
![image](https://user-images.githubusercontent.com/107109/95843011-91efec80-0d8a-11eb-9bf3-8534171b9545.png)

Possibly related to #5 
```
Traceback (most recent call last):
  File "limitswap.py", line 303, in start_bot
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1499, in call_contract_function
  File "eth_utils\functional.py", line 45, in inner
  File "web3\eth.py", line 432, in call
  File "web3\manager.py", line 149, in request_blocking
  File "web3\manager.py", line 128, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\gas_price_strategy.py", line 34, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\exception_retry_request.py", line 105, in middleware
  File "web3\providers\rpc.py", line 92, in make_request
  File "web3\_utils\request.py", line 40, in make_post_request
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://focused-bhabha:cramp-chill-curtly-sedan-cosmos-filler@nd-138-966-059.p2pify.com/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 303, in start_bot
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1499, in call_contract_function
  File "eth_utils\functional.py", line 45, in inner
  File "web3\eth.py", line 432, in call
  File "web3\manager.py", line 149, in request_blocking
  File "web3\manager.py", line 128, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 76, in apply_formatters
  File "web3\middleware\gas_price_strategy.py", line 34, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3\middleware\formatting.py", line 74, in apply_formatters
  File "web3\middleware\exception_retry_request.py", line 105, in middleware
  File "web3\providers\rpc.py", line 92, in make_request
  File "web3\_utils\request.py", line 40, in make_post_request
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://focused-bhabha:cramp-chill-curtly-sedan-cosmos-filler@nd-138-966-059.p2pify.com/
INFO - 2020-10-13 10:29:50,423 - Starting Basic Bot
```

**Comment by CryptoGnome** [comment]
Resolved
