### ISSUE TITLE
Error on "Validate JSON"

### ISSUE THREAD

**Issue by sidework** [CryptoGnome/LimitSwap#84]
When starting up and hitting "Validate JSON" link, the following error occurs because I don't have a "default" folder from the ZIP:
Current version = v2.84
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Dec/2020 13:03:55] "←[37mGET / HTTP/1.1←[0m" 200 -
[2020-12-12 13:04:09,880] ERROR in app: Exception on /validate [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "app.py", line 656, in validate
  File "ext_validate.py", line 60, in validate_GUI_settings
  File "ext_validate.py", line 7, in validate_fetch_default_GUI_settings_json
FileNotFoundError: [Errno 2] No such file or directory: 'default/GUI/GUI_settings.json'
127.0.0.1 - - [12/Dec/2020 13:04:09] "←[35m←[1mGET /validate HTTP/1.1←[0m" 500 -

**Comment by CryptoGnome** [comment]
resolved in v2.85
