### ISSUE TITLE
Cannot sell - LimitSwap.Alpha.v2.61

### ISSUE THREAD

**Issue by goneale** [CryptoGnome/LimitSwap#9]
I am yet to have a successful sell on any version. Just tried triggering a sell manually by lowering the sell price to current price, it attempted and crashed.

You can see it pretty clearly here.

![image](https://user-images.githubusercontent.com/107109/96205907-0d2fe900-0fab-11eb-9e26-63ffa5ea5bb5.png)

```
INFO - 2020-10-16 12:20:55,390 - Using <web3.main.Web3 object at 0x00000203285EFCA0> ('mainnet')
INFO - 2020-10-16 12:20:55,664 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000203285FCB20>
INFO - 2020-10-16 12:20:57,026 - Using <web3.main.Web3 object at 0x00000203286C0F40> ('mainnet')
INFO - 2020-10-16 12:20:57,263 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000203286AF850>
INFO - 2020-10-16 12:20:58,632 - Starting Basic Bot
ERROR - 2020-10-16 12:21:17,117 - 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "limitswap.py", line 346, in start_bot
  File "limitswap.py", line 288, in start
  File "limitswap.py", line 185, in run_bot
  File "limitswap.py", line 264, in sell
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 458, in make_trade
  File "uniswap\uniswap.py", line 546, in _token_to_eth_swap_input
  File "uniswap\uniswap.py", line 91, in check_version
  File "uniswap\uniswap.py", line 316, in get_token_eth_input_price
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
INFO - 2020-10-16 12:21:18,433 - Starting Basic Bot
ERROR - 2020-10-16 12:21:21,097 - 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "limitswap.py", line 346, in start_bot
  File "limitswap.py", line 288, in start
  File "limitswap.py", line 185, in run_bot
  File "limitswap.py", line 264, in sell
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 458, in make_trade
  File "uniswap\uniswap.py", line 546, in _token_to_eth_swap_input
  File "uniswap\uniswap.py", line 91, in check_version
  File "uniswap\uniswap.py", line 316, in get_token_eth_input_price
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 346, in start_bot
  File "limitswap.py", line 288, in start
  File "limitswap.py", line 185, in run_bot
  File "limitswap.py", line 264, in sell
  File "uniswap\uniswap.py", line 78, in approved
  File "uniswap\uniswap.py", line 458, in make_trade
  File "uniswap\uniswap.py", line 546, in _token_to_eth_swap_input
  File "uniswap\uniswap.py", line 91, in check_version
  File "uniswap\uniswap.py", line 316, in get_token_eth_input_price
  File "web3\contract.py", line 875, in __call__
  File "web3\contract.py", line 880, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
INFO - 2020-10-16 12:21:22,560 - Starting Basic Bot
INFO - 2020-10-16 12:21:36,702 - NEW STARTUP v2.5
INFO - 2020-10-16 12:21:37,736 - Using <web3.main.Web3 object at 0x00000164E65CFCA0> ('mainnet')
INFO - 2020-10-16 12:21:38,011 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000164E65DCB20>
INFO - 2020-10-16 12:21:38,804 - Using <web3.main.Web3 object at 0x00000164E66A1F40> ('mainnet')
INFO - 2020-10-16 12:21:39,008 - Using factory contract: <web3._utils.datatypes.Contract object at 0x00000164E668F850>
INFO - 2020-10-16 12:21:40,646 - Starting Basic Bot
```

**Comment by CryptoGnome** [comment]
Fixed for next release TY for the detailed report!
