### ISSUE TITLE
Limitswap retryonfail set to 1 -> breaking .JSON file

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#92]
Limitswap after 1 failed TX has broken .json file and stopped working.

**When I try to relaunch I get following error:**
Current version = v2.83
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5005/ (Press CTRL+C to quit)
[2020-12-16 09:22:45,304] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "app.py", line 421, in index
    stopped = LimitSwap_fetch_stopped()
  File "ext_LimitSwap.py", line 84, in LimitSwap_fetch_stopped
    stopped_pairs = json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 108002 column 60 (char 2354405)
127.0.0.1 - - [16/Dec/2020 09:22:45] "[35m[1mGET / HTTP/1.1[0m" 500 -

**Comment by CryptoGnome** [comment]
please update, current version is v2.85
