### ISSUE TITLE
Error in one of your JSON files. Please Come in Discord for Help!

### ISSUE THREAD

**Issue by NobleVision** [CryptoGnome/LimitSwap#98]
Error in one of your JSON files. Please Come in Discord for Help!

2021-01-02 02:35:39.713588 Error in one of your JSON files. Please Come in Discord for Help!
2021-01-02 02:35:39.714602Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "limitswap.py", line 698, in start_bot
  File "limitswap.py", line 134, in pre_approve
  File "limitswap.py", line 84, in fetch_abi
  File "limitswap.py", line 50, in write_abi
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NobleVision** [comment]
It is working now after disabling the UNN token.  I'll check the contract number.

**Comment by NobleVision** [comment]
Token UNN with contract ID '0x226f7b842e0f0120b7e194d05432b3fd14773a9d' causes the script to fail.

**Comment by NobleVision** [comment]
Removing form JSON file and adding it back in the UI and in the 'tokens.json' file did not resolve the issue.

**Comment by NobleVision** [comment]
![image](https://user-images.githubusercontent.com/16945474/103475925-7855b400-4d7f-11eb-92dd-1529bf95e33a.png)

**Comment by CryptoGnome** [comment]
Please use the discord for support.
